### ISSUE TITLE
2.0/Improve conversions handling

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#292]
Conversions are scattered everywhere and should preferably only happen in two places, binding to cql operator method when arguments are matched/converted against existing methods, and then again on the return type if necessary

This is a big task, so all work will be done across several PR's and on a side branch [develop-2.0-bindings](https://github.com/FirelyTeam/firely-cql-sdk/tree/develop-2.0-bindings)

## TODO's
- [x] Synchronize names between ICqlOperators methods, and the values on the CqlOperator enum
- [x] There is no need to call methods`...OrNull(...)` e.g. `SelectOrNull(...)`, since nullability hints are available in the result type of the method. (Causes all generated c# output to change)
- [x] Park the Choice type generator in another branch, until needed

Comments from PR #303
- [x] Fix the **unnecessary casts** from a value type to its nullable value type e.g. [var o_ = context.Operators.Quantity((decimal?)40m, "%");](https://github.com/FirelyTeam/firely-cql-sdk/pull/303/files/4f159df9d414193481f52fcde28622f2bd93cd13#diff-b2645f821ef513fac4fbc49440ca1775a70e602e730606efee77c39e4021df5f)
- [x] The generated code that handles **choice elements** is wrong.  These were treated as DateType in the old code, but are now turned into an object. [Instead of calling Convert on them (which invoked specific logic to turn a DateType into a string), this has changed into a as string now](https://github.com/FirelyTeam/firely-cql-sdk/pull/303/files#r1582645244), which will not invoke the specific logic in the TypeConverter.
- [ ] Converting **Enums** to Strings in [CqlOperatorsBinding.Conversions.cs](https://github.com/FirelyTeam/firely-cql-sdk/pull/303/files/4f159df9d414193481f52fcde28622f2bd93cd13#diff-35c58660127ea2de46a7c2d9feb58eaa3266228838112b54435ec5066a26e36a) : This is not good enough for the fhir pocos, and we should involve the model, probably by asking the specific type converter to convert the enum to a string (e.g. in the firely pocos, you need to call GetLiteral() on an enum value to get to the code).
- [x] The new algorithm actually translates [Code<T> to a string instead of to an enum](https://github.com/FirelyTeam/firely-cql-sdk/pull/303/files/4f159df9d414193481f52fcde28622f2bd93cd13#diff-8cd7efeb09fc8967014bba47af049bcfbd30e44270e05a558837fdadae451701). That should be an improvement, but maybe some parts of the code was dependent on this. Something to keep in mind if we see difference in behaviour when dealing with enums.<br>This can be changed to going through the Convert method again, if necessary, by commenting out this code in `ExpressionBuilder.PropertyHelper`.
![image](https://github.com/FirelyTeam/firely-cql-sdk/assets/4639799/028d8337-ad30-4934-bfd0-a7fae0658dc8)
- [ ] Converting [DataType into a string](https://github.com/FirelyTeam/firely-cql-sdk/pull/303/files/4f159df9d414193481f52fcde28622f2bd93cd13#diff-c831712e7e16c2ad024a7013fa82e80766c9b0072186b6abc96e4fdbb6ce5f7c) requires scrutiny: a DataType has become an object, then in the old code the datatype is converted using Convert to a string, then assigned to display. In the new code, this object is just cast to a string, without call to Convert - which is almost certainly wrong, unless the SelectOrNull converts this - but the lambda ae_ does not seem to do that.
- [x] Remove that abstract class and just have a CqlContextBinder. Likewise, the same for the base type of CqlOperatorsBinder
- [x] Remove the [ReSharper settings file](https://github.com/FirelyTeam/firely-cql-sdk/pull/303/files/4f159df9d414193481f52fcde28622f2bd93cd13#diff-f1af9a69c66a746c5b1b864b1998daa079dd3374333147c107e890c4fd7fefb9)
- [ ] Add code documentation as to what the [difference is between the LibrarySetDefitions and LibraryDefinitions](https://github.com/FirelyTeam/firely-cql-sdk/pull/306/files/5122fbeb44a961b4ac3bf559e4e14d6398bbf885#r1582863864)

**Comment by EvanMachusakNCQA** [comment]
`SelectOrNull` exists because if you call the standard LINQ `Select` method with a `null` source you get an `ArgumentNullException`.  In CQL, if you attempt to do the equivalent of a `Select` (i.e., a Query) when the source is `null`, the result is `null`, not an exception.
